[package]
name = "lw_hotkey_daemon"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "lw_hotkey_daemon"
path = "src/main.rs"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.52", features = [
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Foundation",
] }

[profile.release]
opt-level = 3
